name: first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  http: ^1.1.0
  
  # OTP and phone number packages
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  
  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_app_check: ^0.3.2+10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  google_sign_in: ^6.3.0
  firebase_analytics: ^11.6.0
  firebase_messaging: ^15.2.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lifedrop.png
