// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JpL6amVNGY4UcSl6j4vlQQ2ijdb9I9A',
    appId: '1:982614924050:web:aa7f2e2a7431e91a2e31cb',
    messagingSenderId: '982614924050',
    projectId: 'life-drop-c05df',
    authDomain: 'life-drop-c05df.firebaseapp.com',
    databaseURL: 'https://life-drop-c05df-default-rtdb.firebaseio.com',
    storageBucket: 'life-drop-c05df.firebasestorage.app',
    measurementId: 'G-5QDGEJYLJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_v67mzjyv6Ly4wHILvWemgb_FJuSyTU',
    appId: '1:982614924050:android:5598d3fe1c56e44c2e31cb',
    messagingSenderId: '982614924050',
    projectId: 'life-drop-c05df',
    databaseURL: 'https://life-drop-c05df-default-rtdb.firebaseio.com',
    storageBucket: 'life-drop-c05df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYP11Ve5E5aIpRoyl9B2_bHM1Mu-rCK6I',
    appId: '1:982614924050:ios:99be5529a3b26d842e31cb',
    messagingSenderId: '982614924050',
    projectId: 'life-drop-c05df',
    databaseURL: 'https://life-drop-c05df-default-rtdb.firebaseio.com',
    storageBucket: 'life-drop-c05df.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYP11Ve5E5aIpRoyl9B2_bHM1Mu-rCK6I',
    appId: '1:982614924050:ios:99be5529a3b26d842e31cb',
    messagingSenderId: '982614924050',
    projectId: 'life-drop-c05df',
    databaseURL: 'https://life-drop-c05df-default-rtdb.firebaseio.com',
    storageBucket: 'life-drop-c05df.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5JpL6amVNGY4UcSl6j4vlQQ2ijdb9I9A',
    appId: '1:982614924050:web:201ab7402c8531ca2e31cb',
    messagingSenderId: '982614924050',
    projectId: 'life-drop-c05df',
    authDomain: 'life-drop-c05df.firebaseapp.com',
    databaseURL: 'https://life-drop-c05df-default-rtdb.firebaseio.com',
    storageBucket: 'life-drop-c05df.firebasestorage.app',
    measurementId: 'G-EXR1Y11SHY',
  );
}
